server:
  port: 9091
mybatis-plus:
  mapper-locations: mapper/*.xml
  type-aliases-package: com.heaven.pojo
spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver