spring:
  datasource:
    url: jdbc:mysql://192.168.64.5:3306/blog?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    username: root
    password: match.123
  redis:
    port: 6379
    host: 192.168.64.5
    password: match.123